### ISSUE TITLE
Microsoft Teams schema

### ISSUE THREAD

**Issue by JulienRavet** [MicrosoftDocs/office-365-management-api#110]
Hi,

We're trying to figure out what is the purpose of the Microsoft Teams schema (https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema#microsoft-teams-schema).
The description is quite generic,
> "Extends the Common schema with the properties specific to all Microsoft Teams events."

and we can't find any content on our tenant.

Does anybody know what it's supposed to contain/ be used for ? Is there any roadmap of adding Teams content to the API ?

Regards

**Comment by markjjo** [comment]
@JulienRavet The Teams schema is used to return auditing events related to Microsoft Teams. See:

https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance#microsoft-teams-activities

https://docs.microsoft.com/en-us/microsoftteams/audit-log-events

**Comment by JulienRavet** [comment]
Thank you for the link, very useful.
Do you know if having the Teams user activity (message, like, etc..) in the API can be expected in the future ?
