### ISSUE TITLE
Dynamics schema is missing

### ISSUE THREAD

**Issue by rykoma** [MicrosoftDocs/office-365-management-api#134]
The following page does not have Dynamics 365 schema information, even though we can get logs of Dynamics using Office 365 Management Activity API.

https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema  
https://github.com/MicrosoftDocs/office-365-management-api/blob/live/office-365-management-api/office-365-management-activity-api-schema.md  

For example, we can get a Dynamics log like below (some values are masked):

```json
  {
    "CreationTime": "2019-12-24T06:01:09",
    "Id": "11111111-42f2-43ca-a38c-1b4c737453c2",
    "Operation": "CrmDefaultActivity",
    "OrganizationId": "11111111-a4ac-4fae-bb88-4549cb43e0f2",
    "RecordType": 21,
    "ResultStatus": "Success",
    "UserKey": "Unknown",
    "UserType": 0,
    "Version": 1,
    "Workload": "CRM",
    "ClientIP": "52.163.88.69:50749",
    "ObjectId": "UpdateRibbonClientMetadata ",
    "UserId": "Unknown",
    "CrmOrganizationUniqueName": "orgc111a6c1",
    "Fields": [],
    "InstanceUrl": "https://contoso.crm5.dynamics.com/",
    "ItemType": "Dynamics365",
    "ItemUrl": "https://contoso.crm5.dynamics.com/",
    "UserAgent": "crm-bts-jobs/1.0",
    "CorrelationId": "00000000-0000-0000-0000-000000000000",
    "EntityId": "00000000-0000-0000-0000-000000000000",
    "EntityName": "Unknown",
    "Message": "UpdateRibbonClientMetadata",
    "PrimaryFieldValue": "",
    "Query": "",
    "QueryResults": "",
    "ServiceContextId": "00000000-0000-0000-0000-000000000000",
    "ServiceContextIdType": "",
    "ServiceName": "Dynamics365",
    "SystemUserId": "11111111-aed6-428b-adfc-a441cb413dd3",
    "UserUpn": ""
  }
```

But, there is no description of CrmOrganizationUniqueName or InstanceUrl on the documentation.

Do you have any plan to update the documentation to include Dynamics schema information?

**Comment by markjjo** [comment]
@rykoma Dynamics 365 schema added. Also, see https://docs.microsoft.com/power-platform/admin/enable-use-comprehensive-auditing
