### ISSUE TITLE
Skype for Business workflow schema is missing in the Office 365 Management Activity API schema documentation

### ISSUE THREAD

**Issue by tjorxwrynch** [MicrosoftDocs/office-365-management-api#135]
I'm working on a project that utilizes the Office 365 Management API and deserializes the JSON that is returned by the API to .Net Core objects in order report on O365 audit metrics. When capturing data today, I encountered a workflow that I hadn't seen before titled "SkypeForBusiness" and my application threw an exception because it didn't know what to do with some the serialized data. I went back to see if I missed it when I was creating objects from the "Office 365 Management Activity API schema" documentation and didn't see a reference it there. Here is what the JSON object for that workflow looks like:

```
{
"CreationTime": "",
        "Id": "",
        "Operation": "",
        "OrganizationId": "",
        "RecordType": 23,
        "ResultStatus": "",
        "UserKey": "",
        "UserType": "",
        "Version": "",
        "Workload": "SkypeForBusiness",
        "UserId": "",
        "SkypeForBusinessEventType": "",
        "TenantName": "",
        "CmdletVersion": "",
        "ExternalAccess": false,
        "ObjectName": "",
        "Parameters": [
            {
                "Name": "",
                "Value": ""
            }
        ]
    }
```

---
# Edit 2020-01-13, 12:00 EST
I looked at the JSON object and created an object from it. Thought I would share this information with you in case it helps you update the documentation:

## Skype for Business Workflow
```
        public string SkypeForBusinessEventType { get; set; }
        public string TenantName { get; set; }
        public bool ExternalAccess { get; set; }
        public string ObjectName { get; set; }
```

## Properties in the Skype for Business schema that are shared with Security and Compliance
```
        public List<KeyValuePair<string, string>> Parameters { get; set; }
        public string CmdletVersion { get; set; }
```

## Additional Information
The property "Parameters" is listed as Edm.String in the Security and Compliance schema but the description sounds like it could be a list of <KeyValuePair<string,string>>. If not, it is a string in the Security and Compliance workflow and a list of KeyValuePair<string, string> in Skype for Business.

**Comment by markjjo** [comment]
@tjorxwrynch This is the schema for Skype for Business cmdlets (RecordType=23). I assume that the Operation property contains the cmdlet name that was executed. Here is annotated schema which might help. Other properties in the record are from base Skype for Business audit schema. I think the ObjectName is the object that was acted upon by the cmdlet. 

HTHs

<?xml version="1.0" encoding="utf-8" ?> 
- <edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
- <edmx:Reference Uri="http://schema.audit.exchange.microsoft.com">
  <edmx:Include Alias="Common" Namespace="Microsoft.Office.Audit.Schema" /> 
  </edmx:Reference>
- <edmx:DataServices>
BaseType="SkypeForBusinessBaseAuditRecord">
  <Annotation Term="Microsoft.Office.Audit.Schema.RecordType" EnumMember="Microsoft.Office.Audit.Schema.AuditLogRecordType/SkypeForBusinessCmdlets" /> 
-  
  <Property Name="CmdletVersion" Type="Edm.String" /> 
-  
  <Property Name="ClientApplicationName" Type="Edm.String" /> 
-  
- <Property Name="Parameters" Type="Collection(Common.NameValuePair)">
 
  </Property>
-  
- <Property Name="ModifiedProperties" Type="Collection(Common.ModifiedProperty)">
  <Annotation Term="Microsoft.Office.Audit.Schema.PIIFlag" Bool="true" /> 
  </Property>
-  
  <Property Name="OriginatingServer" Type="Edm.String" /> 
-  
  <Property Name="ExternalAccess" Type="Edm.Boolean" /> 
-  
- <Property Name="ObjectName" Type="Edm.String">
  <Annotation Term="Microsoft.Office.Audit.Schema.PIIFlag" Bool="true" />

**Comment by markjjo** [comment]
@tjorxwrynch Sorry, looks like previous message was cut off. Trying again:

      Property Name="CmdletVersion (Type="Edm.String) #The build version of the cmdlet when it was executed.
      Property Name="ClientApplicationName" Type="Edm.String" #Name of the application that executed this cmdlet. For example, remote powershell, powershell web services, Skype UX, Skype app, etc.
      Property Name="Parameters" Type="Collection(Common.NameValuePair)" #The name and value for parameters that were used.
      Property Name="ModifiedProperties" Type="Collection(Common.ModifiedProperty)" # A collection of 3-tuples (Name, NewValue, PreviousVaule) for each property that was modified.
      Property Name="OriginatingServer" Type="Edm.String" #Name or FQDN of server that executed the cmdlet.
      Property Name="ExternalAccess" Type="Edm.Boolean" #False if the user if from the organization being modified. True otherwise.
      Property Name="ObjectName" Type="Edm.String" #Resolved name of the ObjectId.
