### ISSUE TITLE
Email message events Self.Policy missing policy definitions

### ISSUE THREAD

**Issue by dbuschIH** [MicrosoftDocs/office-365-management-api#150]
Office 365 Advanced Threat Protection and Threat Investigation and Response schema
Email message events
Policy	Self.Policy 
https://github.com/MicrosoftDocs/office-365-management-api/blob/live/office-365-management-api/office-365-management-activity-api-schema.md#policy-type-and-action-type

There are 14 policies listed and defined.
Currently pulling logs under our account into our SIEM. I am seeing 2 additional policies policy 15 and Policy 17 which tells me there might be more policies defined for this table then are published.
How can I get a listing of all active policies so I know what policies these are relating to in our SIEM.

**Comment by markjjo** [comment]
@dbuschIH Thanks for the heads up about this. I just got the following info from engineering. I will add it to the schema topic. Note that we are also looking into enum value #16, which might not be released yet. Here is info for 15 and 17.


|Value | Member Name | Description | 
|-- | -- | -- |
15 | Anti-Spam, High confidence Phish Email | High confidence Phish policy  action in Anti- Spam policy | 
17 | Anti-Spam, Outbound spam policy | Policy Action in the outbound  spam filter policy in Anti-Spam |
