### ISSUE TITLE
AuditLogRecordType  needs to be updated as I find a new record with value 50

### ISSUE THREAD

**Issue by KalapJo1** [MicrosoftDocs/office-365-management-api#172]
Can you please update the audit log record type list as the Content URI is returning a record with value **50** and There is nothing mentioned against the Enum: **AuditLogRecordType** - Type: Edm.Int32

**Comment by markjjo** [comment]
@KalapJo1 Thanks for heads up. Audit records with RecordType = 50 are related to the MailItemsAccessed mailbox auditing action (which requires E5 user license). For more information, see https://docs.microsoft.com/en-us/microsoft-365/compliance/mailitemsaccessed-forensics-investigations?view=o365-worldwide

I will add RecordType 50 to the schema documentation.
