### ISSUE TITLE
Incorrect Sample Schema: Get Current Status and Get Historical Status

### ISSUE THREAD

**Issue by Daleyon** [MicrosoftDocs/office-365-management-api#207]
Hello,
The sample schemas for Get Current Status and Get Historical Status are incorrect.

"StatusDisplayName" is new

- Old: StatusDate / New: "StatusTime"

- Old: FeatureGroupStatusCollection / New: "FeatureStatus"

"FeatureStatus" collection includes the following new:

- "FeatureDisplayName"
- "FeatureName"
- "FeatureServiceStatus"
- "FeatureServiceStatusDisplayName"

https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-service-communications-api-reference#sample-response-1
https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-service-communications-api-reference#sample-response-2

Current response provided (snipit sample and not full):
 "Id": "Exchange",
      "IncidentIds": [
        "EX231425",
        "EX229923"
      ],
      "Status": "ServiceDegradation",
      "StatusDisplayName": "Service degradation",
      "StatusTime": "2020-12-27T16:13:24.1214338Z",
      "Workload": "Exchange",
      "WorkloadDisplayName": "Exchange Online"
    },
    {
      "FeatureStatus": [
        {
          "FeatureDisplayName": "Service",
          "FeatureName": "service",
          "FeatureServiceStatus": "ServiceOperational",
          "FeatureServiceStatusDisplayName": "Normal service"
        },
        {
          "FeatureDisplayName": "Form functionality",
          "FeatureName": "functionality",
          "FeatureServiceStatus": "ServiceOperational",
          "FeatureServiceStatusDisplayName": "Normal service"
        },
        {
          "FeatureDisplayName": "Integration",
          "FeatureName": "integration",
          "FeatureServiceStatus": "ServiceOperational",
          "FeatureServiceStatusDisplayName": "Normal service"
        }
      ],
"Id": "Lync",
      "IncidentIds": [],
      "Status": "ServiceOperational",
      "StatusDisplayName": "Normal service",
      "StatusTime": "2020-12-27T16:13:24.1214338Z",
      "Workload": "Lync",
      "WorkloadDisplayName": "Skype for Business"
    },
    {
      "FeatureStatus": [
        {
          "FeatureDisplayName": "Other",
          "FeatureName": "MicroFLowOther",
          "FeatureServiceStatus": "ServiceOperational",
          "FeatureServiceStatusDisplayName": "Normal service"
        },
        {
          "FeatureDisplayName": "Service and web access issues",
          "FeatureName": "Service",
          "FeatureServiceStatus": "ServiceOperational",
          "FeatureServiceStatusDisplayName": "Normal service"
        }
      ],

**Comment by lindalu-MSFT** [comment]
@Daleyon If still applicable, please create a PR with your proposed changes. Thanks, Linda
