### ISSUE TITLE
Quarantined mails due to Spam cannot be retrieved via Office 365 Management API

### ISSUE THREAD

**Issue by marcsantamaria-aiq** [MicrosoftDocs/office-365-management-api#222]
Hi,

We have followed https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-reference to retrieve content from Office 365 Management API and we are able to retrieve information from all mails quarantined due to Malware or Phishing, but those due to Spam (Policy Type - Hosted content filter policy) is not possible to retrieve them.

Is there any other ContentType that should be used or some configuration that is required to be able to retrieve them?

Thanks!

**Comment by marcsantamaria-aiq** [comment]
@markjjo for visibility

**Comment by markjjo** [comment]
@marcsantamaria-aiq Please contact/open a ticket with Microsoft Support about this issue/question.
