### ISSUE TITLE
Data fields in Microsoft Office 365 Reporting Add-on for Splunk

### ISSUE THREAD

**Issue by robarismail97** [MicrosoftDocs/office-365-management-api#271]
Hi,

I have created an app in Azure given the permissions to the Office 365 management activity API and also created the Microsoft Office 365 Reporting Add-on in Splunk. The results when searching is not covering the fields i want. I want to get the subject of the email which Defender for O365 has triggered an alert on. Is the API sending the data? If yes, where is the fields stuck? I'm trying to do the searches outside the applicatin with a index=* search and I still don't get all the schemas listed in https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema

Br,

Robar

**Comment by markjjo** [comment]
@robarismail97 Please open a ticket with MS Support. Based on the info you provide about your tenant and more detail about what you're trying to do they and engineering should be able to help/propose other options.
