### ISSUE TITLE
content?

### ISSUE THREAD

**Issue by LucLabelle** [MicrosoftDocs/office-365-management-api#5]
The call to content? doesn't seem to work with the dates parameters. 

This line (copied from article) : Invoke-WebRequest -Method GET -Headers $headerParams -Uri https://manage.office.com/api/v1.0/$tenantGUID/activity/feed/subscriptions/content?contentType=Audit.SharePoint &startTime=2017-10-13T000:00&endTime=2017-10-13T11:59

Generates this error : 
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At line:1 char:199

**Comment by Linda-Editor** [comment]
I put the entire string in quotes:

```powershell
Invoke-WebRequest -Method GET -Headers $headerParams -Uri "https://manage.office.com/api/v1.0/$tenantGUID/activity/feed/subscriptions/content?contentType=Audit.SharePoint&startTime=2017-10-13T00:00&endTime=2017-10-13T11:59"
```

Let me know if this doesn't fix it.  Wait an hour or so until the changes are pushed.
