### ISSUE TITLE
Incorrect description for startTime and endTime

### ISSUE THREAD

**Issue by vergnes** [MicrosoftDocs/office-365-management-api#52]
The documentation states that `startTime` and `endTime`:
 1) are optional and if not provided the last 24 hours time range will be used
 2) both must be specified or both omitted

Currently what I observe is:
 1) `startTime` or `endTime` must be provided otherwise the response is a 400 HTTP error with following body:
```
{
    "error": {
        "code": "String reference not set to an instance of a String.\r\nParameter name",
        "message": "s"
    }
}
```
 2) The API can be called with only `startTime` or `endTime` specified until they respect the 7 days constraint

**Comment by lindalu-MSFT** [comment]
@vergnes If still applicable, please create a PR with your proposed changes. Or open a new issue with the link to the topic with the incorrect description. Thanks, linda
