### ISSUE TITLE
Lack of possible responses

### ISSUE THREAD

**Issue by yyyogev** [MicrosoftDocs/office-365-management-api#89]
Besides the error list at the end, there are many responses that can be returned upon calls that aren't documented. The one that bugs me the most is:
`"error": {
        "code": "StartSubscription [TenantId=5b9a99a5-************-4279ec819ed6,ContentType=Audit.Exchange,ApplicationId=de113d70-************-1790e19d3016,PublisherId=00000000-0000-0000-0000-000000000000] failed. Exception",
        "message": "Microsoft.Office.Compliance.Audit.DataServiceException: Tenant 5b9a99a5-*****************-4279ec819ed6 does not exist.\r\n   at Microsoft.Office.Compliance.Audit.API.AzureManager.GetSubscriptionTableClientForTenant(Guid tenantID, Boolean throwIfTenantNull)\r\n   at Microsoft.Office.Compliance.Audit.API.AzureManager.<GetAPISubscriptionAsync>d__22.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Office.Compliance.Audit.API.StartController.<StartSubscription>d__0.MoveNext()"
    }`

when making this request:
`https://manage.office.com/api/v1.0/5b9a99a5-************-4279ec819ed6/activity/feed/subscriptions/start?contentType=Audit.Exchange
Headers: 
Authorization: Bearer {{access_token}}
Content-Type: application/x-www-form-urlencoded
`
I'm not sure if I'm getting this because of this request or because of the initial request (the one I'm requesting the access token). Either way, this response seems to make no sense since I already got the token with this tenant.

I didn't find any mention for this message and I have no lead on how to solve it.
Please help
Thanks

**Comment by himan20** [comment]
Getting the same issue as described by @yyyogev, can anybody provide any help on this?
Im trying to fetch data for contentType=Audit.Sharepoint and already got the access token for the tenantId, however, starting a subscription always throws the above error.

**Comment by yyyogev** [comment]
@markjjo

**Comment by niharaobsec** [comment]
We're also seeing the same. The responses are inconsistent. At times retries work. Other times, you have to give it a few minutes before retrying.

**Comment by Sk0ttz** [comment]
We're also experiencing  this issue. No inconsistent responses though,  just this same response every time. Like others we successfully requested an access token.

Exception", "message": "Microsoft.Office.Compliance.Audit.DataServiceException: Tenant *** does not exist.\r\n at Microsoft.Office.Compliance.Audit.API.AzureManager.GetSubscriptionTableClientForTenant(Guid tenantID, Boolean throwIfTenantNull)\r\n at Microsoft.Office.Compliance.Audit.API.AzureManager

**Comment by maimaisie** [comment]
We are experiencing the same thing for some tenants. Starting subscription fails with different content types.

**Comment by himan20** [comment]
We solved it by raising a support ticket with Microsoft and they started the subscription from their end; it works now.

**Comment by markjjo** [comment]
@yyyogev @Sk0ttz RE: "Microsoft.Office.Compliance.Audit.DataServiceException: Tenant *** does not exist - Be sure that unified auditing is enabled for your Office 365 organization. To enable, see https://docs.microsoft.com/en-us/office365/securitycompliance/turn-audit-log-search-on-or-off  

We just added this heads up to the documentation.

**Comment by yyyogev** [comment]
It works!! 
Thanks you!

**Comment by Titoleto** [comment]
In my case, I have the same issue and the problem Unified Auditing is enabled, the problem is with Authorization Url in custom connector. By default, Authorization Url comes with: http://login.microsoftonline.com but if I change it to the value https://login.windows.net then it works correctly

**Comment by DanishIbrar12** [comment]
> In my case, I have the same issue In my case, I have enabled Unified Auditing but my problem is with Authorization Url in custom connector. By default, Authorization Url comes with: http://login.microsoftonline.com but if I change it to the value https://login.windows.net then it works correctly
where do you change this???

**Comment by Titoleto** [comment]
> ot sure if I'm getting this because of this request or because of the initial request (the one I'm requesting the access token). Either way, this response seems to make no sense since I already got the token with this tenant.

In my case, I changed it by editing a Custom Connector (Office 365 Management API) in the Security section that was used in an older version of the CoE Starter Kit, but it is now deprecated, so we no longer have it.
