### ISSUE TITLE
replace Old link 

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/office-365-management-api#9]
The link to the ADAL libraries point to obsolete documentation, it would be more helpful if it pointed to somewhere like https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-libraries

**Comment by Linda-Editor** [comment]
Thank you for your contribution. I've updated the link. Changes should be live in the next hour or so.

**Comment by LucLabelle** [comment]
Welcome,

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
